name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make
        
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
      
    - name: Build project
      run: cmake --build build --config ${{ matrix.build-type }}
    
    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure
